### ISSUE TITLE
Comments not filtered by post

### ISSUE THREAD

**Issue by JIntrocaso** [1hitsong/AOS#39]
When getting the comments for a post using the Lemmy API, it seems to bring back all comments. Everything looks like it is being set up property and passed to the client. The issue might lie upstream of us in either the client or the api itself. Just wanted to document this here for now as something that will need addressing.

**Comment by 1hitsong** [comment]
Found the issue. The API call fetchPostComments within lemmyAPI.js isn't being passed props, it's being passed the postID itself.

So change the function param to postID and remove the props const and you're good to go.

![image](https://github.com/1hitsong/AOS/assets/3330318/ebe0f4b3-22d7-4ab6-862e-b6010d0d448c)

**Comment by JIntrocaso** [comment]
Good call. That was the fix.

**Comment by JIntrocaso** [comment]
Fixed with PR #38
